name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install numpy pandas pytest

    - name: Run tests
      working-directory: DigitalNumbers
      run: |
        python tests/chapter2_linear_systems/test_LU_simple.py
        python tests/chapter2_linear_systems/test_LU_partial_pivoting.py
        python tests/chapter2_linear_systems/test_crout.py
        python tests/chapter2_linear_systems/test_doolittle.py
        python tests/chapter2_linear_systems/test_cholesky.py
        python tests/chapter4_interpolation/test_vandermonde.py
        python tests/chapter4_interpolation/test_jacobi.py
        python tests/chapter4_interpolation/test_gauss-seidel.py
        python tests/chapter4_interpolation/test_sor.py
